site_name: Generative AI + Prompt Engineering
site_description: Intensive course  (3 horas)
site_author: Marilola Afonso -- ULPGC

docs_dir: docs
site_dir: site

theme:
  name: material
  language: es
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

nav:
  - Home: index.md
  - "Block I – Introduction": block1/block1.md
  - "Block II – Prompt Engineering": block2/block2.md
  - "Block III – Context Engineering": block3/block3.md
  - "Block IV – Tools": block4/block4.md
  - "Block V – Practical Application": block5/block5.md
